export const supportedLocales = [
  { code: "pt-BR", label: "Português (Brasil)", shortLabel: "PT" },
  { code: "en", label: "English", shortLabel: "EN" },
  { code: "fr", label: "Français", shortLabel: "FR" },
  { code: "it", label: "Italiano", shortLabel: "IT" },
  { code: "es", label: "Español", shortLabel: "ES" },
  { code: "de", label: "Deutsch", shortLabel: "DE" },
  { code: "ru", label: "Русский", shortLabel: "RU" },
  { code: "da", label: "Dansk", shortLabel: "DA" },
  { code: "no", label: "Norsk", shortLabel: "NO" },
] as const;

export type LocaleCode = (typeof supportedLocales)[number]["code"];

export const LOCALE_STORAGE_KEY = "wesley-portfolio-locale";

export const portraitStatusLabels: Record<LocaleCode, string> = {
  "pt-BR": "DISPONÍVEL",
  en: "AVAILABLE",
  fr: "DISPONIBLE",
  it: "DISPONIBILE",
  es: "DISPONIBLE",
  de: "VERFÜGBAR",
  ru: "ДОСТУПЕН",
  da: "TILGÆNGELIG",
  no: "TILGJENGELIG",
};

type StepCopy = { title: string; description: string };

export type PortfolioCopy = {
  navigation: [string, string, string, string, string];
  languageButton: string;
  languageMenuLabel: string;
  availability: [string, string];
  eyebrow: string;
  heroTitle: [string, string];
  heroIntro: string;
  heroActions: [string, string];
  metrics: [string, string, string];
  explore: string;
  vision: { index: string; title: [string, string]; intro: string; action: string; cards: [StepCopy, StepCopy, StepCopy] };
  method: { index: string; title: [string, string]; steps: [StepCopy, StepCopy, StepCopy] };
  projects: {
    index: string;
    title: [string, string];
    latest: string;
    loading: string;
    noProject: string;
    description: string;
    error: string;
    tags: [string, string, string];
    visit: string;
    viewAll: string;
    catalogLabel: string;
    catalogTitle: string;
    closeCatalog: string;
    loadingCatalog: string;
    catalogError: string;
    emptyCatalog: string;
    previewLoading: string;
    previewLoadingDetail: string;
    previewUnavailable: string;
    previewUnavailableDetail: string;
    directLink: string;
    descriptions: Record<string, string>;
    defaultDescription: string;
  };
  stack: { index: string; title: [string, string]; intro: string; groups: [StepCopy, StepCopy, StepCopy] };
  contact: { index: string; title: [string, string]; intro: string; email: string; whatsapp: string };
  footer: { backToTop: string };
  cookies: {
    dialogLabel: string;
    heading: string;
    intro: string;
    essential: string;
    essentialDetail: string;
    alwaysActive: string;
    measurement: string;
    measurementDetail: string;
    preferences: string;
    close: string;
    save: string;
    essentialOnly: string;
    acceptAll: string;
  };
};

const projectDescriptions = {
  pt: {
    "wesley-portfolio-studio": "Portfólio de engenharia com vitrine dinâmica de projetos e experiências visuais de profundidade.",
    altixdev: "Site institucional da Altixdev para apresentar software sob medida, automações e produtos digitais.",
    portifolio: "Portfólio anterior com apresentação profissional, projetos e serviços de engenharia full stack.",
    espacoglamour: "Experiência digital para salão de beleza com serviços, localização e canais de contato.",
    projetoverdeacao: "Plataforma de mobilização ambiental para voluntariado, campanhas e transformação coletiva.",
  },
  en: {
    "wesley-portfolio-studio": "Engineering portfolio with a dynamic project showcase and layered visual experiences.",
    altixdev: "Altixdev's institutional website presenting bespoke software, automation, and digital products.",
    portifolio: "Previous portfolio featuring professional presentation, projects, and full-stack engineering services.",
    espacoglamour: "Digital experience for a beauty salon with services, location, and contact channels.",
    projetoverdeacao: "Environmental engagement platform for volunteers, campaigns, and collective transformation.",
  },
  fr: {
    "wesley-portfolio-studio": "Portfolio d’ingénierie avec une vitrine dynamique de projets et des expériences visuelles en profondeur.",
    altixdev: "Site institutionnel d’Altixdev présentant des logiciels sur mesure, des automatisations et des produits numériques.",
    portifolio: "Ancien portfolio présentant des projets et des services d’ingénierie full stack.",
    espacoglamour: "Expérience numérique pour un salon de beauté avec services, localisation et canaux de contact.",
    projetoverdeacao: "Plateforme de mobilisation environnementale pour bénévoles, campagnes et transformation collective.",
  },
  it: {
    "wesley-portfolio-studio": "Portfolio di ingegneria con vetrina dinamica dei progetti ed esperienze visive stratificate.",
    altixdev: "Sito istituzionale di Altixdev per presentare software su misura, automazioni e prodotti digitali.",
    portifolio: "Portfolio precedente con presentazione professionale, progetti e servizi di ingegneria full stack.",
    espacoglamour: "Esperienza digitale per un salone di bellezza con servizi, posizione e canali di contatto.",
    projetoverdeacao: "Piattaforma di mobilitazione ambientale per volontari, campagne e trasformazione collettiva.",
  },
  es: {
    "wesley-portfolio-studio": "Portafolio de ingeniería con una vitrina dinámica de proyectos y experiencias visuales en profundidad.",
    altixdev: "Sitio institucional de Altixdev para presentar software a medida, automatizaciones y productos digitales.",
    portifolio: "Portafolio anterior con presentación profesional, proyectos y servicios de ingeniería full stack.",
    espacoglamour: "Experiencia digital para salón de belleza con servicios, ubicación y canales de contacto.",
    projetoverdeacao: "Plataforma de movilización ambiental para voluntariado, campañas y transformación colectiva.",
  },
  de: {
    "wesley-portfolio-studio": "Engineering-Portfolio mit dynamischer Projektgalerie und visuellen Tiefenerlebnissen.",
    altixdev: "Unternehmenswebsite von Altixdev für maßgeschneiderte Software, Automatisierung und digitale Produkte.",
    portifolio: "Früheres Portfolio mit professioneller Präsentation, Projekten und Full-Stack-Engineering-Leistungen.",
    espacoglamour: "Digitale Erfahrung für einen Schönheitssalon mit Leistungen, Standort und Kontaktmöglichkeiten.",
    projetoverdeacao: "Umweltplattform für Freiwilligenarbeit, Kampagnen und kollektive Veränderung.",
  },
  ru: {
    "wesley-portfolio-studio": "Инженерное портфолио с динамической витриной проектов и многослойным визуальным опытом.",
    altixdev: "Корпоративный сайт Altixdev для презентации заказного ПО, автоматизации и цифровых продуктов.",
    portifolio: "Предыдущее портфолио с профессиональной презентацией, проектами и full-stack услугами.",
    espacoglamour: "Цифровой опыт для салона красоты с услугами, местоположением и каналами связи.",
    projetoverdeacao: "Платформа экологической мобилизации для волонтёрства, кампаний и коллективных изменений.",
  },
  da: {
    "wesley-portfolio-studio": "Ingeniørportefølje med dynamisk projektudstilling og visuelle oplevelser i dybden.",
    altixdev: "Altixdevs virksomhedssite for skræddersyet software, automatisering og digitale produkter.",
    portifolio: "Tidligere portefølje med professionel præsentation, projekter og full-stack-ydelser.",
    espacoglamour: "Digital oplevelse for en skønhedssalon med tjenester, placering og kontaktkanaler.",
    projetoverdeacao: "Platform for miljøengagement, frivillighed, kampagner og fælles forandring.",
  },
  no: {
    "wesley-portfolio-studio": "Ingeniørportefølje med dynamisk prosjektutstilling og visuelle dybdeopplevelser.",
    altixdev: "Altixdevs bedriftsnettsted for skreddersydd programvare, automatisering og digitale produkter.",
    portifolio: "Tidligere portefølje med profesjonell presentasjon, prosjekter og fullstack-tjenester.",
    espacoglamour: "Digital opplevelse for en skjønnhetssalong med tjenester, beliggenhet og kontaktkanaler.",
    projetoverdeacao: "Plattform for miljøengasjement, frivillighet, kampanjer og felles endring.",
  },
} as const;

const createCopy = (copy: PortfolioCopy) => copy;

export const portfolioCopies: Record<LocaleCode, PortfolioCopy> = {
  "pt-BR": createCopy({
    navigation: ["Início", "Visão", "Projeto", "Stack", "Contato"], languageButton: "Idioma", languageMenuLabel: "Selecionar idioma", availability: ["Aberto a projetos", "e parcerias."], eyebrow: "ENGENHEIRO DE SOFTWARE / FULL STACK", heroTitle: ["Da operação complexa", "a sistemas claros."], heroIntro: "Sou Wesley Barroso. Projeto aplicações, integrações e automações que dão escala ao que realmente move o seu negócio.", heroActions: ["Ver trabalho selecionado", "Iniciar uma conversa"], metrics: ["Produtos digitais", "Automações úteis", "Arquitetura escalável"], explore: "EXPLORE",
    vision: { index: "01 / VISÃO DE ENTREGA", title: ["Engenharia que se", "enxerga no resultado."], intro: "Trabalho entre o detalhe técnico e a necessidade de negócio. Isso significa ouvir o processo, desenhar a arquitetura certa e entregar experiências que não criam mais fricção.", action: "Vamos mapear a sua operação", cards: [{ title: "Sistemas conectados", description: "APIs e integrações para transformar ferramentas isoladas em fluxos consistentes." }, { title: "Automação com intenção", description: "Processos que reduzem tarefas repetitivas e deixam a equipe focada no que exige decisão." }, { title: "Produtos que evoluem", description: "Interfaces e estruturas pensadas para manter performance quando o negócio cresce." }] },
    method: { index: "02 / MÉTODO", title: ["Clareza para decidir.", "Rigor para construir."], steps: [{ title: "Descobrir", description: "Entender a rotina, os limites e o objetivo da operação." }, { title: "Estruturar", description: "Definir experiência, dados, integrações e caminho de escala." }, { title: "Entregar", description: "Construir, validar e evoluir a solução em ciclos objetivos." }] },
    projects: { index: "03 / VITRINE VERCEL", title: ["Seu trabalho mais recente,", "sempre em produção."], latest: "PROJETO MAIS RECENTE NO VERCEL", loading: "ATUALIZANDO PROJETO", noProject: "Aguardando projeto ativo", description: "Este card é atualizado pela sua conta Vercel e sempre mostra o último projeto com deployment ativo em produção.", error: "A integração Vercel precisa ser concluída para exibir o projeto mais recente.", tags: ["Vercel", "Produção", "Atualizado recentemente"], visit: "Visitar projeto", viewAll: "Ver meus projetos", catalogLabel: "CATÁLOGO / VERCEL", catalogTitle: "Projetos ativos", closeCatalog: "Fechar lista de projetos", loadingCatalog: "Carregando os projetos ativos da sua conta Vercel.", catalogError: "Não foi possível atualizar a lista agora. Tente novamente em alguns instantes.", emptyCatalog: "Nenhum projeto ativo foi encontrado nesta conta Vercel.", previewLoading: "CARREGANDO PRÉVIA", previewLoadingDetail: "Preparando a visualização ao vivo.", previewUnavailable: "PRÉVIA INDISPONÍVEL", previewUnavailableDetail: "Use “Visitar projeto” para abrir a versão publicada.", directLink: "LINK DIRETO", descriptions: projectDescriptions.pt, defaultDescription: "Projeto ativo publicado em produção e atualizado a partir da conta Vercel." },
    stack: { index: "04 / FERRAMENTAS, NÃO ENFEITES", title: ["Decisões técnicas para", "sistemas que duram."], intro: "A stack não é uma coleção de logos. É um conjunto de decisões para cada contexto, equipe e velocidade de evolução.", groups: [{ title: "Interfaces", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Serviços", description: "Node.js · APIs REST · Express · Supabase" }, { title: "Dados & entrega", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / PRÓXIMO PASSO", title: ["Uma boa solução começa", "com uma conversa clara."], intro: "Se você tem um processo para melhorar, uma ideia para validar ou um produto para estruturar, podemos desenhar o próximo passo juntos.", email: "Escrever um e-mail", whatsapp: "Falar no WhatsApp" }, footer: { backToTop: "VOLTAR AO TOPO" }, cookies: { dialogLabel: "Preferências de cookies", heading: "PRIVACIDADE E COOKIES", intro: "Usamos cookies essenciais para lembrar sua preferência. Tecnologias opcionais só serão autorizadas com o seu consentimento.", essential: "Essenciais", essentialDetail: "Sempre ativos para manter suas preferências.", alwaysActive: "Sempre ativo", measurement: "Medição de experiência", measurementDetail: "Ajuda a entender como o portfólio é utilizado.", preferences: "Preferências", close: "Fechar", save: "Salvar preferências", essentialOnly: "Somente essenciais", acceptAll: "Aceitar todos" },
  }),
  en: createCopy({
    navigation: ["Home", "Vision", "Project", "Stack", "Contact"], languageButton: "Language", languageMenuLabel: "Select language", availability: ["Open to projects", "and partnerships."], eyebrow: "SOFTWARE ENGINEER / FULL STACK", heroTitle: ["From complex operations", "to clear systems."], heroIntro: "I’m Wesley Barroso. I design applications, integrations, and automations that scale what truly moves your business.", heroActions: ["View selected work", "Start a conversation"], metrics: ["Digital products", "Useful automation", "Scalable architecture"], explore: "EXPLORE",
    vision: { index: "01 / DELIVERY VISION", title: ["Engineering you", "can see in the result."], intro: "I work between technical detail and business needs. That means listening to the process, designing the right architecture, and delivering experiences that create less friction.", action: "Let’s map your operation", cards: [{ title: "Connected systems", description: "APIs and integrations that turn isolated tools into consistent flows." }, { title: "Intentional automation", description: "Processes that reduce repetitive work and keep teams focused on decisions." }, { title: "Products that evolve", description: "Interfaces and structures built to sustain performance as the business grows." }] },
    method: { index: "02 / METHOD", title: ["Clarity to decide.", "Rigor to build."], steps: [{ title: "Discover", description: "Understand the routine, constraints, and goal of the operation." }, { title: "Structure", description: "Define experience, data, integrations, and the path to scale." }, { title: "Deliver", description: "Build, validate, and evolve the solution in focused cycles." }] },
    projects: { index: "03 / VERCEL SHOWCASE", title: ["Your latest work,", "always in production."], latest: "LATEST PROJECT ON VERCEL", loading: "UPDATING PROJECT", noProject: "Waiting for an active project", description: "This card is updated from your Vercel account and always shows the latest project with an active production deployment.", error: "The Vercel integration must be completed to show the latest project.", tags: ["Vercel", "Production", "Recently updated"], visit: "Visit project", viewAll: "View my projects", catalogLabel: "CATALOG / VERCEL", catalogTitle: "Active projects", closeCatalog: "Close project list", loadingCatalog: "Loading active projects from your Vercel account.", catalogError: "The list could not be updated now. Please try again shortly.", emptyCatalog: "No active project was found in this Vercel account.", previewLoading: "LOADING PREVIEW", previewLoadingDetail: "Preparing the live view.", previewUnavailable: "PREVIEW UNAVAILABLE", previewUnavailableDetail: "Use “Visit project” to open the published version.", directLink: "DIRECT LINK", descriptions: projectDescriptions.en, defaultDescription: "Active project published in production and updated from the Vercel account." },
    stack: { index: "04 / TOOLS, NOT ORNAMENTS", title: ["Technical decisions for", "systems that last."], intro: "A stack is not a collection of logos. It is a set of decisions for each context, team, and pace of evolution.", groups: [{ title: "Interfaces", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Services", description: "Node.js · REST APIs · Express · Supabase" }, { title: "Data & delivery", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / NEXT STEP", title: ["A good solution starts", "with a clear conversation."], intro: "If you have a process to improve, an idea to validate, or a product to shape, we can design the next step together.", email: "Write an email", whatsapp: "Talk on WhatsApp" }, footer: { backToTop: "BACK TO TOP" }, cookies: { dialogLabel: "Cookie preferences", heading: "PRIVACY AND COOKIES", intro: "We use essential cookies to remember your preference. Optional technologies are only authorized with your consent.", essential: "Essential", essentialDetail: "Always active to keep your preferences.", alwaysActive: "Always active", measurement: "Experience measurement", measurementDetail: "Helps us understand how the portfolio is used.", preferences: "Preferences", close: "Close", save: "Save preferences", essentialOnly: "Essential only", acceptAll: "Accept all" },
  }),
  fr: createCopy({
    navigation: ["Accueil", "Vision", "Projet", "Stack", "Contact"], languageButton: "Langue", languageMenuLabel: "Choisir la langue", availability: ["Ouvert aux projets", "et partenariats."], eyebrow: "INGÉNIEUR LOGICIEL / FULL STACK", heroTitle: ["Des opérations complexes", "à des systèmes clairs."], heroIntro: "Je suis Wesley Barroso. Je conçois des applications, des intégrations et des automatisations qui donnent de l’ampleur à ce qui fait avancer votre activité.", heroActions: ["Voir le travail sélectionné", "Démarrer une conversation"], metrics: ["Produits numériques", "Automatisations utiles", "Architecture évolutive"], explore: "EXPLORER",
    vision: { index: "01 / VISION DE LIVRAISON", title: ["Une ingénierie qui", "se voit dans le résultat."], intro: "Je travaille entre le détail technique et le besoin métier. Cela signifie écouter le processus, concevoir la bonne architecture et livrer des expériences qui créent moins de friction.", action: "Cartographions votre activité", cards: [{ title: "Systèmes connectés", description: "Des API et intégrations qui transforment des outils isolés en flux cohérents." }, { title: "Automatisation intentionnelle", description: "Des processus qui réduisent les tâches répétitives et libèrent l’équipe pour les décisions." }, { title: "Produits qui évoluent", description: "Des interfaces et structures conçues pour durer lorsque l’activité grandit." }] },
    method: { index: "02 / MÉTHODE", title: ["Clarté pour décider.", "Rigueur pour construire."], steps: [{ title: "Découvrir", description: "Comprendre la routine, les limites et l’objectif de l’opération." }, { title: "Structurer", description: "Définir l’expérience, les données, les intégrations et le chemin de croissance." }, { title: "Livrer", description: "Construire, valider et faire évoluer la solution par cycles ciblés." }] },
    projects: { index: "03 / VITRINE VERCEL", title: ["Votre travail le plus récent,", "toujours en production."], latest: "PROJET LE PLUS RÉCENT SUR VERCEL", loading: "MISE À JOUR DU PROJET", noProject: "En attente d’un projet actif", description: "Cette carte est mise à jour depuis votre compte Vercel et affiche toujours le dernier projet avec un déploiement actif en production.", error: "L’intégration Vercel doit être finalisée pour afficher le projet le plus récent.", tags: ["Vercel", "Production", "Mis à jour récemment"], visit: "Visiter le projet", viewAll: "Voir mes projets", catalogLabel: "CATALOGUE / VERCEL", catalogTitle: "Projets actifs", closeCatalog: "Fermer la liste des projets", loadingCatalog: "Chargement des projets actifs depuis votre compte Vercel.", catalogError: "La liste ne peut pas être mise à jour maintenant. Réessayez dans quelques instants.", emptyCatalog: "Aucun projet actif n’a été trouvé sur ce compte Vercel.", previewLoading: "CHARGEMENT DE L’APERÇU", previewLoadingDetail: "Préparation de la vue en direct.", previewUnavailable: "APERÇU INDISPONIBLE", previewUnavailableDetail: "Utilisez « Visiter le projet » pour ouvrir la version publiée.", directLink: "LIEN DIRECT", descriptions: projectDescriptions.fr, defaultDescription: "Projet actif publié en production et mis à jour depuis le compte Vercel." },
    stack: { index: "04 / DES OUTILS, PAS DES ORNEMENTS", title: ["Des décisions techniques pour", "des systèmes qui durent."], intro: "Une stack n’est pas une collection de logos. C’est un ensemble de décisions adapté à chaque contexte, équipe et rythme d’évolution.", groups: [{ title: "Interfaces", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Services", description: "Node.js · API REST · Express · Supabase" }, { title: "Données & livraison", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / PROCHAINE ÉTAPE", title: ["Une bonne solution commence", "par une conversation claire."], intro: "Si vous avez un processus à améliorer, une idée à valider ou un produit à structurer, nous pouvons concevoir la prochaine étape ensemble.", email: "Écrire un e-mail", whatsapp: "Parler sur WhatsApp" }, footer: { backToTop: "RETOUR EN HAUT" }, cookies: { dialogLabel: "Préférences de cookies", heading: "CONFIDENTIALITÉ ET COOKIES", intro: "Nous utilisons des cookies essentiels pour mémoriser votre préférence. Les technologies optionnelles ne sont autorisées qu’avec votre consentement.", essential: "Essentiels", essentialDetail: "Toujours actifs pour conserver vos préférences.", alwaysActive: "Toujours actif", measurement: "Mesure de l’expérience", measurementDetail: "Aide à comprendre l’utilisation du portfolio.", preferences: "Préférences", close: "Fermer", save: "Enregistrer les préférences", essentialOnly: "Essentiels uniquement", acceptAll: "Tout accepter" },
  }),
  it: createCopy({
    navigation: ["Inizio", "Visione", "Progetto", "Stack", "Contatto"], languageButton: "Lingua", languageMenuLabel: "Seleziona lingua", availability: ["Disponibile per progetti", "e partnership."], eyebrow: "INGEGNERE DEL SOFTWARE / FULL STACK", heroTitle: ["Dalle operazioni complesse", "ai sistemi chiari."], heroIntro: "Sono Wesley Barroso. Progetto applicazioni, integrazioni e automazioni che fanno crescere ciò che muove davvero la tua attività.", heroActions: ["Vedi il lavoro selezionato", "Inizia una conversazione"], metrics: ["Prodotti digitali", "Automazioni utili", "Architettura scalabile"], explore: "ESPLORA",
    vision: { index: "01 / VISIONE DI CONSEGNA", title: ["Ingegneria che", "si vede nel risultato."], intro: "Lavoro tra il dettaglio tecnico e le esigenze di business. Significa ascoltare il processo, progettare l’architettura giusta e offrire esperienze con meno attrito.", action: "Mappiamo la tua operazione", cards: [{ title: "Sistemi connessi", description: "API e integrazioni che trasformano strumenti isolati in flussi coerenti." }, { title: "Automazione intenzionale", description: "Processi che riducono le attività ripetitive e lasciano il team concentrato sulle decisioni." }, { title: "Prodotti che evolvono", description: "Interfacce e strutture pensate per mantenere prestazioni mentre il business cresce." }] },
    method: { index: "02 / METODO", title: ["Chiarezza per decidere.", "Rigore per costruire."], steps: [{ title: "Scoprire", description: "Comprendere routine, limiti e obiettivo dell’operazione." }, { title: "Strutturare", description: "Definire esperienza, dati, integrazioni e percorso di crescita." }, { title: "Consegnare", description: "Costruire, validare ed evolvere la soluzione in cicli mirati." }] },
    projects: { index: "03 / VETRINA VERCEL", title: ["Il tuo lavoro più recente,", "sempre in produzione."], latest: "PROGETTO PIÙ RECENTE SU VERCEL", loading: "AGGIORNAMENTO PROGETTO", noProject: "In attesa di un progetto attivo", description: "Questa scheda viene aggiornata dal tuo account Vercel e mostra sempre l’ultimo progetto con un deployment attivo in produzione.", error: "L’integrazione Vercel deve essere completata per mostrare il progetto più recente.", tags: ["Vercel", "Produzione", "Aggiornato di recente"], visit: "Visita progetto", viewAll: "Vedi i miei progetti", catalogLabel: "CATALOGO / VERCEL", catalogTitle: "Progetti attivi", closeCatalog: "Chiudi elenco progetti", loadingCatalog: "Caricamento dei progetti attivi dal tuo account Vercel.", catalogError: "Impossibile aggiornare l’elenco ora. Riprova tra poco.", emptyCatalog: "Nessun progetto attivo trovato in questo account Vercel.", previewLoading: "CARICAMENTO ANTEPRIMA", previewLoadingDetail: "Preparazione della vista dal vivo.", previewUnavailable: "ANTEPRIMA NON DISPONIBILE", previewUnavailableDetail: "Usa “Visita progetto” per aprire la versione pubblicata.", directLink: "LINK DIRETTO", descriptions: projectDescriptions.it, defaultDescription: "Progetto attivo pubblicato in produzione e aggiornato dall’account Vercel." },
    stack: { index: "04 / STRUMENTI, NON ORNAMENTI", title: ["Decisioni tecniche per", "sistemi che durano."], intro: "Lo stack non è una raccolta di loghi. È un insieme di decisioni per ogni contesto, team e ritmo di evoluzione.", groups: [{ title: "Interfacce", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Servizi", description: "Node.js · API REST · Express · Supabase" }, { title: "Dati e consegna", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / PROSSIMO PASSO", title: ["Una buona soluzione inizia", "con una conversazione chiara."], intro: "Se hai un processo da migliorare, un’idea da validare o un prodotto da strutturare, possiamo progettare insieme il prossimo passo.", email: "Scrivi un’e-mail", whatsapp: "Parla su WhatsApp" }, footer: { backToTop: "TORNA IN ALTO" }, cookies: { dialogLabel: "Preferenze cookie", heading: "PRIVACY E COOKIE", intro: "Usiamo cookie essenziali per ricordare la tua preferenza. Le tecnologie opzionali sono autorizzate solo con il tuo consenso.", essential: "Essenziali", essentialDetail: "Sempre attivi per mantenere le tue preferenze.", alwaysActive: "Sempre attivo", measurement: "Misurazione dell’esperienza", measurementDetail: "Aiuta a capire come viene usato il portfolio.", preferences: "Preferenze", close: "Chiudi", save: "Salva preferenze", essentialOnly: "Solo essenziali", acceptAll: "Accetta tutto" },
  }),
  es: createCopy({
    navigation: ["Inicio", "Visión", "Proyecto", "Stack", "Contacto"], languageButton: "Idioma", languageMenuLabel: "Seleccionar idioma", availability: ["Disponible para proyectos", "y alianzas."], eyebrow: "INGENIERO DE SOFTWARE / FULL STACK", heroTitle: ["De operaciones complejas", "a sistemas claros."], heroIntro: "Soy Wesley Barroso. Diseño aplicaciones, integraciones y automatizaciones que escalan lo que realmente mueve tu negocio.", heroActions: ["Ver trabajo seleccionado", "Iniciar una conversación"], metrics: ["Productos digitales", "Automatizaciones útiles", "Arquitectura escalable"], explore: "EXPLORAR",
    vision: { index: "01 / VISIÓN DE ENTREGA", title: ["Ingeniería que", "se ve en el resultado."], intro: "Trabajo entre el detalle técnico y la necesidad del negocio. Eso implica escuchar el proceso, diseñar la arquitectura adecuada y entregar experiencias con menos fricción.", action: "Mapeemos tu operación", cards: [{ title: "Sistemas conectados", description: "APIs e integraciones que transforman herramientas aisladas en flujos consistentes." }, { title: "Automatización intencional", description: "Procesos que reducen tareas repetitivas y dejan al equipo enfocado en las decisiones." }, { title: "Productos que evolucionan", description: "Interfaces y estructuras preparadas para mantener el rendimiento al crecer el negocio." }] },
    method: { index: "02 / MÉTODO", title: ["Claridad para decidir.", "Rigor para construir."], steps: [{ title: "Descubrir", description: "Comprender la rutina, los límites y el objetivo de la operación." }, { title: "Estructurar", description: "Definir experiencia, datos, integraciones y el camino de escala." }, { title: "Entregar", description: "Construir, validar y evolucionar la solución en ciclos enfocados." }] },
    projects: { index: "03 / VITRINA VERCEL", title: ["Tu trabajo más reciente,", "siempre en producción."], latest: "PROYECTO MÁS RECIENTE EN VERCEL", loading: "ACTUALIZANDO PROYECTO", noProject: "Esperando un proyecto activo", description: "Esta tarjeta se actualiza desde tu cuenta de Vercel y siempre muestra el último proyecto con un deployment activo en producción.", error: "La integración con Vercel debe completarse para mostrar el proyecto más reciente.", tags: ["Vercel", "Producción", "Actualizado recientemente"], visit: "Visitar proyecto", viewAll: "Ver mis proyectos", catalogLabel: "CATÁLOGO / VERCEL", catalogTitle: "Proyectos activos", closeCatalog: "Cerrar lista de proyectos", loadingCatalog: "Cargando proyectos activos de tu cuenta Vercel.", catalogError: "No fue posible actualizar la lista ahora. Inténtalo de nuevo en unos instantes.", emptyCatalog: "No se encontró ningún proyecto activo en esta cuenta Vercel.", previewLoading: "CARGANDO VISTA PREVIA", previewLoadingDetail: "Preparando la visualización en vivo.", previewUnavailable: "VISTA PREVIA NO DISPONIBLE", previewUnavailableDetail: "Usa “Visitar proyecto” para abrir la versión publicada.", directLink: "ENLACE DIRECTO", descriptions: projectDescriptions.es, defaultDescription: "Proyecto activo publicado en producción y actualizado desde la cuenta Vercel." },
    stack: { index: "04 / HERRAMIENTAS, NO ADORNOS", title: ["Decisiones técnicas para", "sistemas que perduran."], intro: "El stack no es una colección de logos. Es un conjunto de decisiones para cada contexto, equipo y ritmo de evolución.", groups: [{ title: "Interfaces", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Servicios", description: "Node.js · API REST · Express · Supabase" }, { title: "Datos y entrega", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / PRÓXIMO PASO", title: ["Una buena solución empieza", "con una conversación clara."], intro: "Si tienes un proceso que mejorar, una idea que validar o un producto que estructurar, podemos diseñar juntos el siguiente paso.", email: "Escribir un correo", whatsapp: "Hablar por WhatsApp" }, footer: { backToTop: "VOLVER ARRIBA" }, cookies: { dialogLabel: "Preferencias de cookies", heading: "PRIVACIDAD Y COOKIES", intro: "Usamos cookies esenciales para recordar tu preferencia. Las tecnologías opcionales solo se autorizan con tu consentimiento.", essential: "Esenciales", essentialDetail: "Siempre activas para conservar tus preferencias.", alwaysActive: "Siempre activo", measurement: "Medición de experiencia", measurementDetail: "Ayuda a entender cómo se utiliza el portafolio.", preferences: "Preferencias", close: "Cerrar", save: "Guardar preferencias", essentialOnly: "Solo esenciales", acceptAll: "Aceptar todo" },
  }),
  de: createCopy({
    navigation: ["Start", "Vision", "Projekt", "Stack", "Kontakt"], languageButton: "Sprache", languageMenuLabel: "Sprache auswählen", availability: ["Offen für Projekte", "und Partnerschaften."], eyebrow: "SOFTWAREENTWICKLER / FULL STACK", heroTitle: ["Von komplexen Abläufen", "zu klaren Systemen."], heroIntro: "Ich bin Wesley Barroso. Ich entwickle Anwendungen, Integrationen und Automatisierungen, die das skalieren, was Ihr Unternehmen wirklich bewegt.", heroActions: ["Ausgewählte Arbeit ansehen", "Gespräch beginnen"], metrics: ["Digitale Produkte", "Nützliche Automatisierung", "Skalierbare Architektur"], explore: "ENTDECKEN",
    vision: { index: "01 / LIEFERVISION", title: ["Engineering, das", "im Ergebnis sichtbar wird."], intro: "Ich arbeite zwischen technischem Detail und Geschäftsanforderungen. Das heißt: Prozesse verstehen, die passende Architektur entwickeln und Erlebnisse mit weniger Reibung liefern.", action: "Lassen Sie uns Ihre Abläufe abbilden", cards: [{ title: "Vernetzte Systeme", description: "APIs und Integrationen, die isolierte Tools in konsistente Abläufe verwandeln." }, { title: "Bewusste Automatisierung", description: "Prozesse, die repetitive Arbeit reduzieren und Teams auf Entscheidungen fokussieren." }, { title: "Produkte, die wachsen", description: "Schnittstellen und Strukturen für Leistung, wenn das Unternehmen wächst." }] },
    method: { index: "02 / METHODE", title: ["Klarheit für Entscheidungen.", "Sorgfalt beim Bauen."], steps: [{ title: "Entdecken", description: "Routine, Grenzen und Ziel des Vorhabens verstehen." }, { title: "Strukturieren", description: "Erlebnis, Daten, Integrationen und Skalierungsweg definieren." }, { title: "Liefern", description: "Die Lösung in fokussierten Zyklen bauen, validieren und weiterentwickeln." }] },
    projects: { index: "03 / VERCEL-SCHAUFENSTER", title: ["Ihre neueste Arbeit,", "immer in Produktion."], latest: "NEUESTES PROJEKT AUF VERCEL", loading: "PROJEKT WIRD AKTUALISIERT", noProject: "Warte auf ein aktives Projekt", description: "Diese Karte wird über Ihr Vercel-Konto aktualisiert und zeigt immer das neueste Projekt mit aktivem Produktions-Deployment.", error: "Die Vercel-Integration muss abgeschlossen werden, um das neueste Projekt anzuzeigen.", tags: ["Vercel", "Produktion", "Kürzlich aktualisiert"], visit: "Projekt besuchen", viewAll: "Meine Projekte ansehen", catalogLabel: "KATALOG / VERCEL", catalogTitle: "Aktive Projekte", closeCatalog: "Projektliste schließen", loadingCatalog: "Aktive Projekte aus Ihrem Vercel-Konto werden geladen.", catalogError: "Die Liste kann jetzt nicht aktualisiert werden. Bitte versuchen Sie es gleich erneut.", emptyCatalog: "In diesem Vercel-Konto wurde kein aktives Projekt gefunden.", previewLoading: "VORSCHAU WIRD GELADEN", previewLoadingDetail: "Live-Ansicht wird vorbereitet.", previewUnavailable: "VORSCHAU NICHT VERFÜGBAR", previewUnavailableDetail: "Öffnen Sie mit „Projekt besuchen“ die veröffentlichte Version.", directLink: "DIREKTLINK", descriptions: projectDescriptions.de, defaultDescription: "Aktives Projekt in Produktion, aktualisiert über das Vercel-Konto." },
    stack: { index: "04 / WERKZEUGE, KEIN SCHMUCK", title: ["Technische Entscheidungen für", "Systeme, die bleiben."], intro: "Ein Stack ist keine Logosammlung. Er ist eine Reihe von Entscheidungen für jeden Kontext, jedes Team und jedes Entwicklungstempo.", groups: [{ title: "Oberflächen", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Dienste", description: "Node.js · REST APIs · Express · Supabase" }, { title: "Daten & Lieferung", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / NÄCHSTER SCHRITT", title: ["Eine gute Lösung beginnt", "mit einem klaren Gespräch."], intro: "Wenn Sie einen Prozess verbessern, eine Idee validieren oder ein Produkt strukturieren möchten, können wir gemeinsam den nächsten Schritt entwerfen.", email: "E-Mail schreiben", whatsapp: "Auf WhatsApp sprechen" }, footer: { backToTop: "ZURÜCK NACH OBEN" }, cookies: { dialogLabel: "Cookie-Einstellungen", heading: "DATENSCHUTZ UND COOKIES", intro: "Wir verwenden essenzielle Cookies, um Ihre Auswahl zu speichern. Optionale Technologien werden nur mit Ihrer Zustimmung aktiviert.", essential: "Essentiell", essentialDetail: "Immer aktiv, um Ihre Einstellungen zu speichern.", alwaysActive: "Immer aktiv", measurement: "Nutzungsmessung", measurementDetail: "Hilft zu verstehen, wie das Portfolio genutzt wird.", preferences: "Einstellungen", close: "Schließen", save: "Einstellungen speichern", essentialOnly: "Nur essenzielle", acceptAll: "Alle akzeptieren" },
  }),
  ru: createCopy({
    navigation: ["Главная", "Подход", "Проект", "Стек", "Контакты"], languageButton: "Язык", languageMenuLabel: "Выбрать язык", availability: ["Открыт для проектов", "и партнёрств."], eyebrow: "ИНЖЕНЕР-ПРОГРАММИСТ / FULL STACK", heroTitle: ["От сложных процессов", "к ясным системам."], heroIntro: "Меня зовут Уэсли Баррозу. Я проектирую приложения, интеграции и автоматизации, которые масштабируют то, что действительно двигает ваш бизнес.", heroActions: ["Посмотреть избранную работу", "Начать разговор"], metrics: ["Цифровые продукты", "Полезная автоматизация", "Масштабируемая архитектура"], explore: "ИЗУЧИТЬ",
    vision: { index: "01 / ВИДЕНИЕ РЕЗУЛЬТАТА", title: ["Инженерия, которую", "видно в результате."], intro: "Я работаю на стыке технических деталей и бизнес-задач. Это означает понять процесс, спроектировать верную архитектуру и создать опыт с меньшим трением.", action: "Давайте разберём ваши процессы", cards: [{ title: "Связанные системы", description: "API и интеграции, которые превращают разрозненные инструменты в единые потоки." }, { title: "Осмысленная автоматизация", description: "Процессы, снижающие рутинную работу и оставляющие команде важные решения." }, { title: "Развивающиеся продукты", description: "Интерфейсы и структуры, рассчитанные на производительность при росте бизнеса." }] },
    method: { index: "02 / МЕТОД", title: ["Ясность для решений.", "Точность для создания."], steps: [{ title: "Исследовать", description: "Понять рутину, ограничения и цель операции." }, { title: "Структурировать", description: "Определить опыт, данные, интеграции и путь к масштабированию." }, { title: "Доставить", description: "Создавать, проверять и развивать решение в чётких циклах." }] },
    projects: { index: "03 / ВИТРИНА VERCEL", title: ["Ваша последняя работа,", "всегда в продакшене."], latest: "ПОСЛЕДНИЙ ПРОЕКТ В VERCEL", loading: "ОБНОВЛЕНИЕ ПРОЕКТА", noProject: "Ожидание активного проекта", description: "Эта карточка обновляется из вашей учётной записи Vercel и всегда показывает последний проект с активным production-развёртыванием.", error: "Чтобы показать последний проект, необходимо завершить интеграцию с Vercel.", tags: ["Vercel", "Продакшен", "Недавно обновлено"], visit: "Открыть проект", viewAll: "Мои проекты", catalogLabel: "КАТАЛОГ / VERCEL", catalogTitle: "Активные проекты", closeCatalog: "Закрыть список проектов", loadingCatalog: "Загрузка активных проектов из вашей учётной записи Vercel.", catalogError: "Сейчас не удалось обновить список. Повторите попытку позже.", emptyCatalog: "В этой учётной записи Vercel не найдено активных проектов.", previewLoading: "ЗАГРУЗКА ПРЕДПРОСМОТРА", previewLoadingDetail: "Подготовка живого просмотра.", previewUnavailable: "ПРЕДПРОСМОТР НЕДОСТУПЕН", previewUnavailableDetail: "Откройте опубликованную версию через «Открыть проект».", directLink: "ПРЯМАЯ ССЫЛКА", descriptions: projectDescriptions.ru, defaultDescription: "Активный проект опубликован в продакшене и обновлён из учётной записи Vercel." },
    stack: { index: "04 / ИНСТРУМЕНТЫ, НЕ УКРАШЕНИЯ", title: ["Технические решения для", "систем, которые служат долго."], intro: "Стек — не коллекция логотипов. Это набор решений для каждого контекста, команды и темпа развития.", groups: [{ title: "Интерфейсы", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Сервисы", description: "Node.js · REST API · Express · Supabase" }, { title: "Данные и доставка", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / СЛЕДУЮЩИЙ ШАГ", title: ["Хорошее решение начинается", "с ясного разговора."], intro: "Если вы хотите улучшить процесс, проверить идею или структурировать продукт, мы можем спроектировать следующий шаг вместе.", email: "Написать письмо", whatsapp: "Написать в WhatsApp" }, footer: { backToTop: "НАВЕРХ" }, cookies: { dialogLabel: "Настройки cookie", heading: "КОНФИДЕНЦИАЛЬНОСТЬ И COOKIE", intro: "Мы используем обязательные cookie, чтобы сохранить ваш выбор. Дополнительные технологии включаются только с вашего согласия.", essential: "Обязательные", essentialDetail: "Всегда активны для сохранения настроек.", alwaysActive: "Всегда активно", measurement: "Измерение опыта", measurementDetail: "Помогает понять, как используется портфолио.", preferences: "Настройки", close: "Закрыть", save: "Сохранить настройки", essentialOnly: "Только обязательные", acceptAll: "Принять все" },
  }),
  da: createCopy({
    navigation: ["Hjem", "Vision", "Projekt", "Stack", "Kontakt"], languageButton: "Sprog", languageMenuLabel: "Vælg sprog", availability: ["Åben for projekter", "og partnerskaber."], eyebrow: "SOFTWAREINGENIØR / FULL STACK", heroTitle: ["Fra komplekse processer", "til klare systemer."], heroIntro: "Jeg er Wesley Barroso. Jeg designer applikationer, integrationer og automatiseringer, der skalerer det, som virkelig driver din forretning.", heroActions: ["Se udvalgt arbejde", "Start en samtale"], metrics: ["Digitale produkter", "Nyttig automatisering", "Skalerbar arkitektur"], explore: "UDFORSK",
    vision: { index: "01 / LEVERINGSVISION", title: ["Ingeniørarbejde, som", "ses i resultatet."], intro: "Jeg arbejder mellem tekniske detaljer og forretningsbehov. Det betyder at forstå processen, designe den rette arkitektur og levere oplevelser med mindre friktion.", action: "Lad os kortlægge din drift", cards: [{ title: "Forbundne systemer", description: "API’er og integrationer, der gør isolerede værktøjer til sammenhængende flows." }, { title: "Bevidst automatisering", description: "Processer, der reducerer gentaget arbejde og lader teamet fokusere på beslutninger." }, { title: "Produkter der udvikler sig", description: "Grænseflader og strukturer til at bevare ydeevnen, når forretningen vokser." }] },
    method: { index: "02 / METODE", title: ["Klarhed til at beslutte.", "Grundighed til at bygge."], steps: [{ title: "Opdage", description: "Forstå rutine, begrænsninger og målet med opgaven." }, { title: "Strukturere", description: "Definér oplevelse, data, integrationer og vejen til skala." }, { title: "Levere", description: "Byg, validér og udvikl løsningen i fokuserede cyklusser." }] },
    projects: { index: "03 / VERCEL-UDSTILLING", title: ["Dit nyeste arbejde,", "altid i produktion."], latest: "SENESTE PROJEKT PÅ VERCEL", loading: "OPDATERER PROJEKT", noProject: "Afventer et aktivt projekt", description: "Dette kort opdateres fra din Vercel-konto og viser altid det seneste projekt med en aktiv produktionsudrulning.", error: "Vercel-integrationen skal færdiggøres for at vise det seneste projekt.", tags: ["Vercel", "Produktion", "Nyligt opdateret"], visit: "Besøg projekt", viewAll: "Se mine projekter", catalogLabel: "KATALOG / VERCEL", catalogTitle: "Aktive projekter", closeCatalog: "Luk projektlisten", loadingCatalog: "Indlæser aktive projekter fra din Vercel-konto.", catalogError: "Listen kan ikke opdateres nu. Prøv igen om lidt.", emptyCatalog: "Ingen aktive projekter blev fundet på denne Vercel-konto.", previewLoading: "INDLÆSER FORHÅNDSVISNING", previewLoadingDetail: "Forbereder livevisningen.", previewUnavailable: "FORHÅNDSVISNING IKKE TILGÆNGELIG", previewUnavailableDetail: "Brug “Besøg projekt” for at åbne den udgivne version.", directLink: "DIREKTE LINK", descriptions: projectDescriptions.da, defaultDescription: "Aktivt projekt i produktion og opdateret fra Vercel-kontoen." },
    stack: { index: "04 / VÆRKTØJER, IKKE PYNT", title: ["Tekniske valg til", "systemer der holder."], intro: "En stack er ikke en samling logoer. Det er et sæt beslutninger for hver kontekst, hvert team og udviklingstempo.", groups: [{ title: "Grænseflader", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Tjenester", description: "Node.js · REST API’er · Express · Supabase" }, { title: "Data og levering", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / NÆSTE SKRIDT", title: ["En god løsning starter", "med en klar samtale."], intro: "Hvis du har en proces at forbedre, en idé at validere eller et produkt at strukturere, kan vi designe næste skridt sammen.", email: "Skriv en e-mail", whatsapp: "Tal på WhatsApp" }, footer: { backToTop: "TILBAGE TIL TOPPEN" }, cookies: { dialogLabel: "Cookieindstillinger", heading: "PRIVATLIV OG COOKIES", intro: "Vi bruger nødvendige cookies til at huske dit valg. Valgfrie teknologier aktiveres kun med dit samtykke.", essential: "Nødvendige", essentialDetail: "Altid aktive for at gemme dine indstillinger.", alwaysActive: "Altid aktiv", measurement: "Oplevelsesmåling", measurementDetail: "Hjælper med at forstå, hvordan porteføljen bruges.", preferences: "Indstillinger", close: "Luk", save: "Gem indstillinger", essentialOnly: "Kun nødvendige", acceptAll: "Acceptér alle" },
  }),
  no: createCopy({
    navigation: ["Hjem", "Visjon", "Prosjekt", "Stack", "Kontakt"], languageButton: "Språk", languageMenuLabel: "Velg språk", availability: ["Åpen for prosjekter", "og partnerskap."], eyebrow: "PROGRAMVAREINGENIØR / FULL STACK", heroTitle: ["Fra komplekse prosesser", "til klare systemer."], heroIntro: "Jeg er Wesley Barroso. Jeg designer applikasjoner, integrasjoner og automatiseringer som skalerer det som virkelig driver virksomheten din.", heroActions: ["Se utvalgt arbeid", "Start en samtale"], metrics: ["Digitale produkter", "Nyttig automatisering", "Skalerbar arkitektur"], explore: "UTFORSK",
    vision: { index: "01 / LEVERINGSVISJON", title: ["Ingeniørarbeid som", "viser seg i resultatet."], intro: "Jeg jobber mellom tekniske detaljer og forretningsbehov. Det betyr å forstå prosessen, designe riktig arkitektur og levere opplevelser med mindre friksjon.", action: "La oss kartlegge driften din", cards: [{ title: "Tilknyttede systemer", description: "API-er og integrasjoner som gjør isolerte verktøy til sammenhengende flyter." }, { title: "Bevisst automatisering", description: "Prosesser som reduserer gjentakende arbeid og lar teamet fokusere på beslutninger." }, { title: "Produkter som utvikler seg", description: "Grensesnitt og strukturer som opprettholder ytelse når virksomheten vokser." }] },
    method: { index: "02 / METODE", title: ["Klarhet til å bestemme.", "Nøyaktighet til å bygge."], steps: [{ title: "Oppdage", description: "Forstå rutine, begrensninger og mål for oppgaven." }, { title: "Strukturere", description: "Definere opplevelse, data, integrasjoner og veien til skalering." }, { title: "Levere", description: "Bygge, validere og utvikle løsningen i fokuserte sykluser." }] },
    projects: { index: "03 / VERCEL-VITRINE", title: ["Ditt nyeste arbeid,", "alltid i produksjon."], latest: "SISTE PROSJEKT PÅ VERCEL", loading: "OPPDATERER PROSJEKT", noProject: "Venter på et aktivt prosjekt", description: "Dette kortet oppdateres fra Vercel-kontoen din og viser alltid det siste prosjektet med en aktiv produksjonsdeploy.", error: "Vercel-integrasjonen må fullføres for å vise det siste prosjektet.", tags: ["Vercel", "Produksjon", "Nylig oppdatert"], visit: "Besøk prosjekt", viewAll: "Se mine prosjekter", catalogLabel: "KATALOG / VERCEL", catalogTitle: "Aktive prosjekter", closeCatalog: "Lukk prosjektlisten", loadingCatalog: "Laster aktive prosjekter fra Vercel-kontoen din.", catalogError: "Listen kan ikke oppdateres nå. Prøv igjen om litt.", emptyCatalog: "Ingen aktive prosjekter ble funnet i denne Vercel-kontoen.", previewLoading: "LASTER FORHÅNDSVISNING", previewLoadingDetail: "Forbereder livevisningen.", previewUnavailable: "FORHÅNDSVISNING IKKE TILGJENGELIG", previewUnavailableDetail: "Bruk «Besøk prosjekt» for å åpne den publiserte versjonen.", directLink: "DIREKTE LENKE", descriptions: projectDescriptions.no, defaultDescription: "Aktivt prosjekt publisert i produksjon og oppdatert fra Vercel-kontoen." },
    stack: { index: "04 / VERKTØY, IKKE PYNT", title: ["Tekniske valg for", "systemer som varer."], intro: "En stack er ikke en samling logoer. Det er et sett med beslutninger for hver kontekst, hvert team og utviklingstempo.", groups: [{ title: "Grensesnitt", description: "React · TypeScript · JavaScript · SCSS" }, { title: "Tjenester", description: "Node.js · REST API-er · Express · Supabase" }, { title: "Data og levering", description: "PostgreSQL · MongoDB · Docker · Linux" }] },
    contact: { index: "05 / NESTE STEG", title: ["En god løsning starter", "med en tydelig samtale."], intro: "Hvis du har en prosess å forbedre, en idé å validere eller et produkt å strukturere, kan vi utforme neste steg sammen.", email: "Skriv en e-post", whatsapp: "Snakk på WhatsApp" }, footer: { backToTop: "TILBAKE TIL TOPPEN" }, cookies: { dialogLabel: "Cookie-innstillinger", heading: "PERSONVERN OG COOKIES", intro: "Vi bruker nødvendige cookies for å huske valget ditt. Valgfrie teknologier aktiveres bare med samtykket ditt.", essential: "Nødvendige", essentialDetail: "Alltid aktive for å bevare innstillingene dine.", alwaysActive: "Alltid aktiv", measurement: "Opplevelsesmåling", measurementDetail: "Hjelper oss å forstå hvordan porteføljen brukes.", preferences: "Innstillinger", close: "Lukk", save: "Lagre innstillinger", essentialOnly: "Bare nødvendige", acceptAll: "Godta alle" },
  }),
};

export function isLocaleCode(value: string | null): value is LocaleCode {
  return supportedLocales.some((locale) => locale.code === value);
}

export function getPortfolioCopy(locale: LocaleCode): PortfolioCopy {
  return portfolioCopies[locale];
}
